project:
  type: website

website:
  title: "Data Science for Business Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lectures.qmd
        text: Lectures
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



